// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Something.AspNet.API.Database;


#nullable disable

namespace Something.AspNet.Database.Migrations;

[DbContext(typeof(ApplicationDbContext))]
[Migration("20250522183721_AddedExpiresAtColumnsToSessionsTable")]
partial class AddedExpiresAtColumnsToSessionsTable
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "9.0.5")
            .HasAnnotation("Relational:MaxIdentifierLength", 128);

        SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

        modelBuilder.Entity("Something.AspNet.Database.Models.Session", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTimeOffset>("AccessTokenExpiresAt")
                    .HasColumnType("datetimeoffset");

                b.Property<Guid>("JwtId")
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTimeOffset>("RefreshTokenExpiresAt")
                    .HasColumnType("datetimeoffset");

                b.Property<DateTimeOffset>("SessionExpiresAt")
                    .HasColumnType("datetimeoffset");

                b.Property<DateTimeOffset>("TokensUpdatedAt")
                    .HasColumnType("datetimeoffset");

                b.Property<Guid>("UserId")
                    .HasColumnType("uniqueidentifier");

                b.HasKey("Id");

                b.HasIndex("UserId");

                b.ToTable("Sessions");
            });

        modelBuilder.Entity("Something.AspNet.Database.Models.User", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(32)
                    .HasColumnType("nvarchar(32)");

                b.Property<string>("PasswordHash")
                    .IsRequired()
                    .HasMaxLength(128)
                    .HasColumnType("nvarchar(128)");

                b.HasKey("Id");

                b.ToTable("Users");
            });

        modelBuilder.Entity("Something.AspNet.Database.Models.Session", b =>
            {
                b.HasOne("Something.AspNet.Database.Models.User", null)
                    .WithMany()
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });
#pragma warning restore 612, 618
    }
}
